name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'sbt'
    - name: build protocol
      run: sbt "+ publishLocal"
      working-directory: protocol
    - name: build sbt plugin
      run: sbt "+ publishLocal"
      working-directory: sbt-idea-compiler-indices
    - name: run scripted tests
      run: sbt scripted
      working-directory: sbt-idea-compiler-indices
